<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/12_Combining_Datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import the Data from Kaggle

https://www.kaggle.com/datasets/vainero/restaurants-customers-orders-dataset?utm_source=chatgpt.com

In [72]:
import pandas as pd
df_cities = pd.read_csv("cities.csv")
df_meals = pd.read_csv("meals.csv")
df_orders = pd.read_csv("orders.csv")
df_restaurants = pd.read_csv("restaurants.csv")

Display the head of the colums

In [73]:
display(df_cities.head())
display(df_meals.head())
display(df_orders.head())
display(df_restaurants.head())

   id            city
0   1        Tel Aviv
1   2       Ramat Gan
2   3  Ramat Hasharon
3   4        Herzelia
4   5       Givatayim

   id  restaurant_id  serve_type_id  meal_type_id hot_cold meal_name  price
0   1              1              1             2     Cold    Meal 1  43.22
1   2              1              2             4      Hot    Meal 2  29.22
2   3              1              3             1     Cold    Meal 3  37.34
3   4              1              3             2      Hot    Meal 4  52.41
4   5              1              3             2     Cold    Meal 5  27.75

   id        date              hour  member_id  restaurant_id  total_order
0   1  2020-01-01  11:00:00.0000000         25              6          0.0
1   2  2020-01-01  11:08:00.0000000        122              4          0.0
2   3  2020-01-01  11:10:00.0000000         62             16         39.0
3   4  2020-01-01  11:13:00.0000000        171              9          0.0
4   5  2020-01-01  11:13:00.0000000        152             30        153.0

   id restaurant_name  restaurant_type_id  income_persentage  city_id
0   1    Restaurant 1                   3              0.075        3
1   2    Restaurant 2                   5              0.100        3
2   3    Restaurant 3                   2              0.075        4
3   4    Restaurant 4                   4              0.100        4
4   5    Restaurant 5                   5              0.050        2

Display names of the colums

In [74]:
print("Cities:", df_cities.columns)
print("Meals:", df_meals.columns)
print("Restaurants:", df_restaurants.columns)
print("Orders:", df_orders.columns)

Cities: Index(['id', 'city'], dtype='object')
Meals: Index(['id', 'restaurant_id', 'serve_type_id', 'meal_type_id', 'hot_cold',
       'meal_name', 'price'],
      dtype='object')
Restaurants: Index(['id', 'restaurant_name', 'restaurant_type_id', 'income_persentage',
       'city_id'],
      dtype='object')
Orders: Index(['id', 'date', 'hour', 'member_id', 'restaurant_id', 'total_order'], dtype='object')

#Inner Join

Returns only the rows where there is a match in both tables.

Example: Merge Orders with Restaurants on restaurant_id

In [66]:
orders_restaurants = pd.merge(df_orders, df_restaurants, on="restaurant_id", how="inner")
print(orders_restaurants.head())

   order_id        date              hour  member_id  restaurant_id  \
0         1  2020-01-01  11:00:00.0000000         25              6
1         2  2020-01-01  11:08:00.0000000        122              4
2         3  2020-01-01  11:10:00.0000000         62             16
3         4  2020-01-01  11:13:00.0000000        171              9
4         5  2020-01-01  11:13:00.0000000        152             30

   total_order restaurant_name  restaurant_type_id  income_persentage  city_id
0          0.0    Restaurant 6                   1              0.050        2
1          0.0    Restaurant 4                   4              0.100        4
2         39.0   Restaurant 16                   1              0.075        3
3          0.0    Restaurant 9                   1              0.075        4
4        153.0   Restaurant 30                   4              0.075        1

#Left Join

Returns all rows from the left DataFrame, and matched rows from the right. Non-matching rows will have

In [67]:
orders_restaurants_left = pd.merge(df_orders, df_restaurants, on="restaurant_id", how="left")
print(orders_restaurants_left.head())

   order_id        date              hour  member_id  restaurant_id  \
0         1  2020-01-01  11:00:00.0000000         25              6
1         2  2020-01-01  11:08:00.0000000        122              4
2         3  2020-01-01  11:10:00.0000000         62             16
3         4  2020-01-01  11:13:00.0000000        171              9
4         5  2020-01-01  11:13:00.0000000        152             30

   total_order restaurant_name  restaurant_type_id  income_persentage  city_id
0          0.0    Restaurant 6                   1              0.050        2
1          0.0    Restaurant 4                   4              0.100        4
2         39.0   Restaurant 16                   1              0.075        3
3          0.0    Restaurant 9                   1              0.075        4
4        153.0   Restaurant 30                   4              0.075        1

#Right Join

Returns all rows from the right DataFrame, and matched rows from the left.

In [68]:
orders_restaurants_right = pd.merge(df_orders, df_restaurants, on="restaurant_id", how="right")
print(orders_restaurants_right.head())

   order_id        date              hour  member_id  restaurant_id  \
0         8  2020-01-01  11:19:00.0000000         95              1
1        19  2020-01-01  11:37:00.0000000        181              1
2        60  2020-01-01  13:03:00.0000000         31              1
3        79  2020-01-01  13:52:00.0000000        149              1
4        93  2020-01-01  18:06:00.0000000         43              1

   total_order restaurant_name  restaurant_type_id  income_persentage  city_id
0        95.96    Restaurant 1                   3              0.075        3
1         0.00    Restaurant 1                   3              0.075        3
2       188.99    Restaurant 1                   3              0.075        3
3       215.31    Restaurant 1                   3              0.075        3
4       173.52    Restaurant 1                   3              0.075        3

#Outer Join

Returns all rows from both DataFrames. Non-matching rows get

In [69]:
orders_restaurants_outer = pd.merge(df_orders, df_restaurants, on="restaurant_id", how="outer")
print(orders_restaurants_outer.head())

   order_id        date              hour  member_id  restaurant_id  \
0         8  2020-01-01  11:19:00.0000000         95              1
1        19  2020-01-01  11:37:00.0000000        181              1
2        60  2020-01-01  13:03:00.0000000         31              1
3        79  2020-01-01  13:52:00.0000000        149              1
4        93  2020-01-01  18:06:00.0000000         43              1

   total_order restaurant_name  restaurant_type_id  income_persentage  city_id
0        95.96    Restaurant 1                   3              0.075        3
1         0.00    Restaurant 1                   3              0.075        3
2       188.99    Restaurant 1                   3              0.075        3
3       215.31    Restaurant 1                   3              0.075        3
4       173.52    Restaurant 1                   3              0.075        3

#Chaining Joins (Multiple tables)

Suppose you want to get Orders → Restaurants → Meals → Cities, you can chain merges:

In [71]:
# Merge Orders with Restaurants
orders_restaurants = pd.merge(df_orders, df_restaurants, on="restaurant_id", how="inner")

# Merge the result with Meals
orders_restaurants_meals = pd.merge(orders_restaurants, df_meals, on="restaurant_id", how="inner")

# Merge with Cities
final_df = pd.merge(orders_restaurants_meals, df_cities, on="city_id", how="inner")

print(final_df.head())

   order_id        date              hour  member_id  restaurant_id  \
0         1  2020-01-01  11:00:00.0000000         25              6
1         1  2020-01-01  11:00:00.0000000         25              6
2         1  2020-01-01  11:00:00.0000000         25              6
3         1  2020-01-01  11:00:00.0000000         25              6
4         1  2020-01-01  11:00:00.0000000         25              6

   total_order restaurant_name  restaurant_type_id  income_persentage  \
0          0.0    Restaurant 6                   1               0.05
1          0.0    Restaurant 6                   1               0.05
2          0.0    Restaurant 6                   1               0.05
3          0.0    Restaurant 6                   1               0.05
4          0.0    Restaurant 6                   1               0.05

   city_id  meal_id  serve_type_id  meal_type_id hot_cold meal_name  price  \
0        2       52              1             4      Hot   Meal 52  30.34
1        2       53              2             4      Hot   Meal 53  45.20
2        2       54              2             3     Cold   Meal 54  31.18
3        2       55              2             2     Cold   Meal 55  23.41
4        2       56              3             2      Hot   Meal 56  44.59

        city
0  Ramat Gan
1  Ramat Gan
2  Ramat Gan
3  Ramat Gan
4  Ramat Gan