<a href="https://colab.research.google.com/github/Aditi-dev07/Pandas_Library/blob/Lib/8_Text_Cleaning_up.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Load dataset from kaggel Api

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("skmewati/myntra-sales-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'myntra-sales-dataset' dataset.
Path to dataset files: /kaggle/input/myntra-sales-dataset

In [ ]:
import pandas as pd
import os

# Assuming the dataset is a CSV file inside the downloaded directory
# We need to find the actual file name within the downloaded path
dataset_files = os.listdir(path)
csv_file = None
for file in dataset_files:
    if file.endswith('.csv'):
        csv_file = file
        break

if csv_file:
    dataset_path = os.path.join(path, csv_file)
    df = pd.read_csv(dataset_path)
    display(df.head())
else:
    print("No CSV file found in the dataset directory.")

,brand_name,pants_description,price,MRP,discount_percent,ratings,number_of_ratings
0,WROGN,Men Loose Fit Cotton Jeans,1374.0,2499.0,0.45,4.2,57.0
1,Flying Machine,Men Slim Fit Jeans,1829.0,2999.0,0.39,4.6,5.0
2,Roadster,Men Pure Cotton Jeans,974.0,2499.0,0.61,3.6,1100.0
3,Bene Kleed,Relaxed Fit Denim Jeans,873.0,2299.0,0.62,4.0,4800.0
4,Levis,Men 511 Slim Fit Jeans,1478.0,2899.0,0.49,4.3,264.0

#.str accessor
Allows you to apply string methods to a Series of strings. It provides convenient ways to manipulate text data within a DataFrame or Series.

#str.upper()
This method converts all characters in each string within the Series to uppercase

In [ ]:
lw = df['brand_name'].str.lower()
print(lw.head())

0             wrogn
1    flying machine
2          roadster
3        bene kleed
4             levis
Name: brand_name, dtype: object

#.str.lower()
This method converts all characters in each string within the Series to lowercase.

In [ ]:
lu = df['pants_description'].str.lower()
print(lu.head())

0    men loose fit cotton jeans
1            men slim fit jeans
2         men pure cotton jeans
3       relaxed fit denim jeans
4        men 511 slim fit jeans
Name: pants_description, dtype: object

#.str.replace()
This method replaces occurrences of a specified substring with another substring in each string within the Series.`

In [ ]:
df['pants_description_replaced'] = df['pants_description'].str.replace('Jeans', 'Denim')
display(df[['pants_description', 'pants_description_replaced']].head())

            pants_description  pants_description_replaced
0  Men Loose Fit Cotton Jeans  Men Loose Fit Cotton Denim
1          Men Slim Fit Jeans          Men Slim Fit Denim
2       Men Pure Cotton Jeans       Men Pure Cotton Denim
3     Relaxed Fit Denim Jeans     Relaxed Fit Denim Denim
4      Men 511 Slim Fit Jeans      Men 511 Slim Fit Denim